### ISSUE TITLE
ipvsFrontend.buildService panic

### ISSUE THREAD

**Issue by SpComb** [qmsk/clusterf#4]
clusterf-ipvs crash when adding a new frontend:

```
2015/11/26 15:15:03 config:etcd.watch: set &{Key:/clusterf/services/test/frontend Value:{"ipv4":"10.0.107.1","tcp":1337} Dir:false Expiration:<nil> TTL:0 Nodes:[] ModifiedIndex:27592801 CreatedIndex:27592801}
2015/11/26 15:15:03 config:Etcd.sync set /clusterf/services/test/frontend: &config.Event{Action:"set", Config:(*config.ConfigServiceFrontend)(0xc8201195c0)}
2015/11/26 15:15:03 config.Sync: {Action:set Config:0xc8201195c0}
2015/11/26 15:15:03 clusterf: config set &config.ConfigServiceFrontend{ServiceName:"test", Frontend:config.ServiceFrontend{IPv4:"10.0.107.1", IPv6:"", TCP:0x539, UDP:0x0}}
2015/11/26 15:15:03 clusterf:Service test: Frontend: set {IPv4:10.0.107.1 IPv6: TCP:1337 UDP:0} <- <nil>
2015/11/26 15:15:03 clusterf:Service test: new Frontend: {IPv4:10.0.107.1 IPv6: TCP:1337 UDP:0}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x46a7d2]

goroutine 1 [running]:
github.com/qmsk/clusterf.(*ipvsFrontend).buildService(0x0, 0x60002, 0xc8201f7190, 0xa, 0x0, 0x0, 0x539, 0x4b9129, 0x0, 0x0)
    /home/tjmartti/go/src/github.com/qmsk/clusterf/ipvs_frontend.go:35 +0x82
github.com/qmsk/clusterf.(*ipvsFrontend).add(0x0, 0xc8201f7190, 0xa, 0x0, 0x0, 0xc800000539, 0x0, 0x0)
    /home/tjmartti/go/src/github.com/qmsk/clusterf/ipvs_frontend.go:86 +0x12d
github.com/qmsk/clusterf.(*Service).newFrontend(0xc8201f4630, 0xc8201f7190, 0xa, 0x0, 0x0, 0x539)
    /home/tjmartti/go/src/github.com/qmsk/clusterf/service.go:101 +0x22d
github.com/qmsk/clusterf.(*Service).configFrontend(0xc8201f4630, 0xb4a428, 0x3, 0xc8201195c0)
    /home/tjmartti/go/src/github.com/qmsk/clusterf/service.go:46 +0x45f
github.com/qmsk/clusterf.(*Services).config(0xc8200ebe88, 0xb4a428, 0x3, 0x7fd091f7d968, 0xc8201195c0)
    /home/tjmartti/go/src/github.com/qmsk/clusterf/services.go:110 +0x1084
github.com/qmsk/clusterf.(*Services).ConfigEvent(0xc8200ebe88, 0xb4a428, 0x3, 0x7fd091f7d968, 0xc8201195c0)
    /home/tjmartti/go/src/github.com/qmsk/clusterf/services.go:180 +0xb4
main.main()
    /home/tjmartti/go/src/github.com/qmsk/clusterf/clusterf-ipvs/main.go:154 +0xc10
```

**Comment by SpComb** [comment]
Fixed in 0.4.0 bc96e6b
